### ISSUE TITLE
Extremely bald but add always sharp 

### ISSUE THREAD

**Issue by karmette** [MicrocontrollersDev/Lunar-Client-Alternatives#2]
always show sharpness particles is a feature of Lunar's particle multiplier mod, find always sharp mod at refraction mod folder
[refraction mod folder](https://www.youtube.com/watch?v=u9eYG4zLJEo&)

**Comment by MicrocontrollersDev** [comment]
oh true, but i also don’t want to redirect people to an entire (awful) mods folder. 

his mod also has a lot of problems/inaccuracies (particles appear at wrong place, it still shows particles when blocked with sword but left click, etc) so that makes me want to add refraction’s even less.

i also don’t want to resort to mod reposting, so for the time being, i don’t want to add his. i’ll keep this open until there’s a better solution

**Comment by FaolanX** [comment]
> oh true, but i also don’t want to redirect people to an entire (awful) mods folder.
> 
> his mod also has a lot of problems/inaccuracies (particles appear at wrong place, it still shows particles when blocked with sword but left click, etc) so that makes me want to add refraction’s even less.
> 
> i also don’t want to resort to mod reposting, so for the time being, i don’t want to add his. i’ll keep this open until there’s a better solution

On Hit Particles
https://www.youtube.com/watch?v=0PPR_t-qyfw

**Comment by MicrocontrollersDev** [comment]
forgot that existed, thanks. will add soon

**Comment by MicrocontrollersDev** [comment]
added

**Comment by karmette** [comment]
ok ngl this mod is better
https://www.youtube.com/watch?v=UPqOL3WWhaw
although onhitparticles gives more customization i don't think it allows the actual sharpness particles to show, but all Minecraft particles, but I could be wrong

**Comment by MicrocontrollersDev** [comment]
> ok ngl this mod is better
> [youtube.com/watch?v=UPqOL3WWhaw](https://www.youtube.com/watch?v=UPqOL3WWhaw)
> although onhitparticles gives more customization i don't think it allows the actual sharpness particles to show, but all Minecraft particles, but I could be wrong

looks good

**Comment by karmette** [comment]
unpin this i think lol
